name: "tagged-release"

on:
  push:
    tags:
      - "v*"
permissions: read-all
jobs:
  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Archive Release
        uses: thedoctor0/zip-release@a24011d8d445e4da5935a7e73c1f98e22a439464
        with:
          type: 'zip'
          filename: 'release.zip'
          exclusions: '*.git* /*node_modules/* /*tests/* *tests/* *.github*'

      - name: Upload Release
        uses: ncipollo/release-action@6c75be85e571768fa31b40abf38de58ba0397db5
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
